"""postgres migrate, add place and more

Revision ID: 1bb1a7ae385d
Revises: 
Create Date: 2019-08-19 04:01:50.181566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb1a7ae385d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crypto_tweets', sa.Column('coordinates', sa.String(), nullable=True))
    op.add_column('crypto_tweets', sa.Column('in_reply_to_status_id_str', sa.String(), nullable=True))
    op.add_column('crypto_tweets', sa.Column('in_reply_to_user_id_str', sa.String(), nullable=True))
    op.add_column('crypto_tweets', sa.Column('place', sa.String(), nullable=True))
    op.add_column('crypto_tweets', sa.Column('quoted_status_id_str', sa.String(), nullable=True))
    op.add_column('crypto_tweets', sa.Column('retweeted_status_id_str', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crypto_tweets', 'retweeted_status_id_str')
    op.drop_column('crypto_tweets', 'quoted_status_id_str')
    op.drop_column('crypto_tweets', 'place')
    op.drop_column('crypto_tweets', 'in_reply_to_user_id_str')
    op.drop_column('crypto_tweets', 'in_reply_to_status_id_str')
    op.drop_column('crypto_tweets', 'coordinates')
    # ### end Alembic commands ###
